site_name: Simples Nacional

repo_url: https://github.com/Interacao-Humano-Computador/2022.2-Grupo3-IHC

theme:
  name: material
  language: pt-BR
  font:
    text: Roboto
  
  palette: 
    - scheme: default
      primary: yellow
      accent: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: green
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/favicon.png
  features:
    - header.autohide
    - navigation.tabs
    - navigation.top
    - navigation.indexes

nav:
  - Planejamento: 
    - Projeto: index.md
    - Sites Analisados: Planejamento/SitesAnalisados.md
    - Metodologias e Processos: Planejamento/Metodologia.md
    - Modelo de Design: Planejamento/ModeloDesign.md
    - Ferramentas: Planejamento/Ferramentas.md
    - Heatmap: Planejamento/Heatmap.md
    - Roadmap: Planejamento/Roadmap.md
    - Políticas:
      - Código de Conduta Para Colaboradores: Planejamento/Politicas/CodigoDeConduta.md
      - Política de Contribuição: Planejamento/Politicas/PolitcaDeContribuicao.md
      - Política de Issue: Planejamento/Politicas/PolitcaDeIssue.md
      - Política de Branch: Planejamento/Politicas/PolitcaDeBranch.md
      - Política de Commit: Planejamento/Politicas/PolitcaDeCommit.md
      - Política de Pull Request: Planejamento/Politicas/PolitcaDePR.md
      - Política de Segurança: Planejamento/Politicas/PolitcaDeSeguranca.md
    - Aspectos Éticos: Planejamento/AspectosEticos.md
    - Termo de consentimento: Planejamento/ModeloTermoConsentimento.md
  - Apresentações/Reuniões:
    - Reunioes: Reunioes/index.md
    - Apresentações:
      - 1º Ponto de Controle: Reunioes/Apresentacoes/Entrega1.md
      - 2º Ponto de Controle: Reunioes/Apresentacoes/Entrega2.md
      - 3º Ponto de Controle: Reunioes/Apresentacoes/Entrega3.md
      - 4º Ponto de Controle: Reunioes/Apresentacoes/Entrega4.md
      - 5º Ponto de Controle: Reunioes/Apresentacoes/Entrega5.md
      - 6º Ponto de Controle: Reunioes/Apresentacoes/Entrega6.md
    - Reuniões:
      - 1ª Reunião: Reunioes/Atas/Reuniao1.md
      - 2ª Reunião: Reunioes/Atas/Reuniao2.md
      - 3ª Reunião: Reunioes/Atas/Reuniao3.md
      - 4ª Reunião: Reunioes/Atas/Reuniao4.md
      - 5ª Reunião: Reunioes/Atas/Reuniao5.md
      - 6ª Reunião: Reunioes/Atas/Reuniao6.md
      - 7ª Reunião: Reunioes/Atas/Reuniao7.md
  - Análise de Requisitos:
    - Análise de Tarefas: Tarefas/Analise.md
    - Perfil de Usúarios: Tarefas/perfilUsuario.md
    - Personas: Tarefas/personas.md
    - Cenários: Tarefas/Cenario.md
    - Metas de Usabilidade: Tarefas/MetasUsabilidade.md
    - Características da Plataforma: Tarefas/CaracteristicasPlataforma.md
    - Princípios Gerais: Tarefas/PrincipiosGerais.md
    - Guia de Estilo: Tarefas/GuiaDeEstilo.md
  - Design, Avaliação e Desenvolvimento:
    - introdução: DesignAvaliacaoDesen/index.md
    - 1º Nível:
      - Análise de Tarefas:
        - Planejamento da Avaliação: DesignAvaliacaoDesen/Nivel1/AnaliseDeTarefas/PlanejamentoAvAnaliseDeTarefas.md
        - Planejamento do Relato : DesignAvaliacaoDesen/Nivel1/AnaliseDeTarefas/PlanejamentoResAnaliseTarefas.md
        - Avaliação : DesignAvaliacaoDesen/Nivel1/AnaliseDeTarefas/AvaliacaoAnaliseDeTarefas.md  
        - Relato de Resultados: DesignAvaliacaoDesen/Nivel1/AnaliseDeTarefas/RelatoResultadosAnaliseTarefas.md
      - Storyboard:
        - Planejamento da Avaliação: DesignAvaliacaoDesen/Nivel1/Storyboard/PlanejamentoAvStoryboard.md
        - Planejamento do Relato : DesignAvaliacaoDesen/Nivel1/Storyboard/PlanejamentoRelatoResuStoryboard.md
        - Avaliação : DesignAvaliacaoDesen/Nivel1/Storyboard/AvaliacaoStoryboards.md
        - Relato de Resultados: DesignAvaliacaoDesen/Nivel1/Storyboard/RelatoResultadosStoryboard.md
      - Verificação da 1ª Etapa: DesignAvaliacaoDesen/Nivel1/VerificacaoEtapa1.md
    - 2º Nível:
      - Protótipo de Papel:
        - Planejamento da Avaliação: DesignAvaliacaoDesen/Nivel2/ProtPapel/PlanejamentoProtPapel.md
        - Planejamento do Relato : DesignAvaliacaoDesen/Nivel2/ProtPapel/PlanejamentoRelatoResuProtPapel.md
        - Relato de Resultados: DesignAvaliacaoDesen/Nivel2/ProtPapel/RelatoResultadosProtPapel.md
    - 3º Nível:
      - Protótipo de Alta Fidelidade:
        - Planejamento da Avaliação: DesignAvaliacaoDesen/Nivel3/ProtAltaFidelidade/PlanejamentoProtAlta.md
        - Planejamento do Relato : DesignAvaliacaoDesen/Nivel3/ProtAltaFidelidade/PlanejamentoRelatoResuProtAlta.md
    - Testes Piloto: 
      - Storyboard: DesignAvaliacaoDesen/TestesPiloto/TestePilotoStoryboard.md
      - Analise de Tarefas: DesignAvaliacaoDesen/TestesPiloto/TestepilotoAnaliTarefas.md
      - Avaliação do 1º Nível: DesignAvaliacaoDesen/TermosConsentimento/TermoConsentimentoAvaliacoes.md
      - Protótipo de Papel: DesignAvaliacaoDesen/TestesPiloto/TestePilotoProtPapel.md
    - Termos de consentimento:
      - Avaliação da Analise de Tarefas: DesignAvaliacaoDesen/TermosConsentimento/TermoConsentimentoAnaliseTarefas.md
      - Avaliação do Storyboard: DesignAvaliacaoDesen/TermosConsentimento/TermoConsentimentoStoryboard.md
      - Avaliação do Protótipo de Papel: DesignAvaliacaoDesen/TermosConsentimento/TermoConsentimentoProtPapel.md
  - Verificação:
    - Introdução: Verificacao/index.md
    - Planejamento:
      - Modelo de Design: Verificacao/Planejamento/modeloDesign.md
      - Aspectos Éticos: Verificacao/Planejamento/aspectosEticos.md
      - Termo de Consentimento: Verificacao/Planejamento/termoConsentimento.md
    - Análise de Requisitos:
      - Análise de Tarefas: Verificacao/Tarefas/AnaliseDeTarefas.md
      - Perfil de Usúario: Verificacao/Tarefas/VerificacaoPerfilUsuario.md
      - Cenários: Verificacao/Tarefas/VerificacaoCenarios.md
      - Princípios Gerais: Verificacao/Tarefas/principiosGerais.md
      - Metas de Usabilidade: Verificacao/Tarefas/verificacaoMetasDeUsabilidade.md
      - Características da Plataforma: Verificacao/Tarefas/VerificacaoCaracteristicasPlataforma.md
      - Guia de Estilo: Verificacao/Tarefas/verificacaoGuiaDeEstilo.md
    - Design, Avaliação e Desenvolvimento:
      - 1º Nível:
        - Storyboard:
          - Planejamento do Relato: Verificacao/DesignAvaliacaoDesen/Nivel1/Storyboard/VerificacaoPlanejamentoRelato.md
      - 2º Nível: Verificacao/DesignAvaliacaoDesen/VerificacaoNivel2.md
      - 3º Nível:
        - Protótipo de Alta Fidelidade:
          - Planejamento da Avalição: Verificacao/DesignAvaliacaoDesen/Nivel3/VerificacaoPlanejamentoAvaliacao.md
          - Planejamento do Relato: Verificacao/DesignAvaliacaoDesen/Nivel3/VerificacaoPlanejamentoRelato.md